server:
  port: ${BOT_PORT:30301}
spring:
  application:
    name: ark-dmbot
bot:
  api-url: https://api.telegram.org/
  use-webhook: ${BOT_USE_WEBHOOK}
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  path: ${BOT_PATH}

management:
  info:
    git:
      mode: full
  endpoint:
    metrics:
      enabled: true
    refresh:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: GET